### PR TITLE
[Release] 0.2

### PR DESCRIPTION
**Pull request by jhamman**
@matthewhanson - can we get this out now?

### CODE REVIEW

**Comment by matthewhanson** [comment]
yes we can.

I looked through the Contributing and Readme docs and not clear on how the versioning occurs and how this gets published to PyPi.  Should I just tag it and push to GitHub, and then publish to PyPi manually?  I'm just not sure how to control incrementing the version.

**Comment by jhamman** [comment]
tldr; yes, versioneer will grab the version string from the git tag. 

I don't think we have fully documented the release procedure beyond what wrote [here](https://github.com/pangeo-data/intake-stac/issues/16). [Dask's documentation](https://github.com/dask/dask/blob/master/docs/release-procedure.md) shows the basic steps for releasing with versioneer.

**Comment by jhamman** [comment]
@matthewhanson - unless you have time this morning. I will make the release today.

**Comment by matthewhanson** [comment]
@jhamman I will do it now!

**Pull request merged**
