### PR TITLE
remove skimage dependency

### LINKED ISSUE #30: remove scikit-image dependency
Scikit image is a 20Mb+ dependency. As far as I can tell it is required by intake-xarray (https://github.com/intake/intake-xarray/blob/c01f328d6157d1ba88c93ab6681834ea4c7c70b8/intake_xarray/image.py) so should instead be specified as a requirement of that intake extension and not here? 

I think we could also just remove it and use rasterio to open all images?

### PR DESCRIPTION
**Pull request by jhamman**
closes #30 

cc @scottyhq

### CODE REVIEW

**Comment by scottyhq** [comment]
thanks @jhamman - at some point we should consider a separate pull request to remove the dependency from intake-array https://github.com/intake/intake-xarray/blob/c01f328d6157d1ba88c93ab6681834ea4c7c70b8/intake_xarray/image.py#L60

**Comment by jhamman** [comment]
> thanks @jhamman - at some point we should consider a separate pull request to remove the dependency from intake-array https://github.com/intake/intake-xarray/blob/c01f328d6157d1ba88c93ab6681834ea4c7c70b8/intake_xarray/image.py#L60

I don't think this is a hard dependency but I do think they'll want to keep this as an optional-dependency.

**Comment by trevorskaggs** [comment]
@jhamman Was doing your [walkthrough of intake-stac](https://medium.com/pangeo/introducing-intake-stac-2c988d8e1d30) and seems that this removal might have borked the walkthrough a little! Without the dependency in place, line 2 in this section barks at ya:
image
```
/Library/Python/3.7/site-packages/intake_xarray/image.py in reader(file, chunks, imread, preprocess, coerce_shape)
    146 
    147     if not imread:
--> 148         from skimage.io import imread
    149 
    150     with file as f:

ModuleNotFoundError: No module named 'skimage'
```

`pip install scikit-image` fixed her right up though!

**Comment by jhamman** [comment]
Hi @trevorskaggs - thanks for pointing this out. Intake-xarray uses scikit-image for png data sources. We've gone back and forth a few times here trying to decide what to list as hard dependencies. Right now, we're just listing `sat-stac` and `intake-xarray`, leaving it up to the user to decide on optional dependencies. I'm starting to see the value of adding some documentation outlining what a common set of optional deps may be.

**Pull request merged**
